### ISSUE TITLE
Update code to new std.process

### ISSUE THREAD

**Issue by MartinNowak** [jmcabo/avgtime#5]
There are some nice new cross-platform functions in std.process.
http://dlang.org/phobos/std_process.html#.spawnProcess

**Comment by jmcabo** [comment]
I just made and pushed a SpawnProcess implementation version.
It can be enabled by uncomenting:
      version = SpawnProcess;
at the top of the file.

Sadly, it has a (very small) measurable overhead, and I cannot leave it as default, since I want to rely on this tool for measuring time with the smallest possible overhead.

Depending on the program that is passed to avgtime, this small overhead won't be noticed. But I cannot leave it as default, because one does not know in advance what I or the users will be measuring.

One can easily see it by compiling a test program:
            void main() { }
and using thousands of repetions. The version with SpawnProcess has more "Total time", always, and the minimum times do differ too.
I didn't want this to be true, since the spawnProcess() implementation was so much cleaner. But I tested it several times and this difference was kept in Kubuntu, Windows and OS X.

Since the overhead is systematic, one could still rely on the SpawnProcess implementation for comparing the times of two programs under test. But I still want to get the closest measurement of absolute time possible.

Cheers, and thanks for creating the issue!
I know it took me a long time to reply but things have been crazy busy.
--jmcabo
